feat(orb): take in account comment from CircleCI Partner Engineering …
GitGuardian/gg-shield-orb pull request #5
Opened 2022-03-03 15:21 UTC by jeremyds

…team

2022-03-07 21:57 UTC, EricRibeiro commented on src/@orb.yml
> +      - ggshield scan -v ci
When invoking command-line programs you have to use run: https://circleci.com/docs/2.0/configuration-reference/#run.

The way it is right now probably won't work.

2022-03-07 21:59 UTC, EricRibeiro requested changes
Your `ggshield scan -v ci` command has to be part of a `run` step. Check https://circleci.com/docs/2.0/configuration-reference/#run for more details.

2022-03-08 15:02 UTC, agateau-gg requested changes

2022-03-08 15:02 UTC, agateau-gg commented on src/@orb.yml
> +        default: ""
Any reason we have a default value for `base_revision` and not for `revision`?

2022-03-08 15:02 UTC, agateau-gg commented on src/@orb.yml
>          description: pipeline base_revision
This description is not super helpful. What about something like this: "ID of the first commit to scan. Leave empty to only scan the latest commit."

2022-03-08 15:02 UTC, agateau-gg commented on src/@orb.yml
>          description: pipeline revision
Same thing here, I suggest something like this: "ID of the last commit to scan. Leave empty to scan up to the latest commit".

2022-03-08 15:02 UTC, agateau-gg commented on src/@orb.yml
> +                base_revision: <<pipeline.git.base_revision>>
.circleci/config.yml uses spaces inside the brackets, this file does not. I don't have strong opinions on which one is best, but it should be the same in all files.

2022-03-28 07:06 UTC, merged